modName = Server Localization
modId = serverlocalization
modGroup = ru.glitchless.serverlocalization
modVersion = 1.2.0
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
enableModernJavaSyntax = false
enableGenericInjection = false
generateGradleTokenClass = ru.glitchless.serverlocalization.Tags
gradleTokenVersion = VERSION
disableSpotless = true
disableCheckstyle = true
includeWellKnownRepositories = true
usesMavenPublishing = false
usesMixins = true
mixinsPackage = mixin
autoUpdateBuildScript = false
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Proxy configuration for accessing GTNH Maven / Gradle distributions
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897
